---
title: "Untitled"
author: "Dan Spakowicz and Rebecca Hoyd"
date: "October 15, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(CausalImpact)
library(nlme)
library(lubridate)
library(tidyverse)
library(ggpubr)
```



```{r load data}
load("../data/modeldf.Rdata")

nohop <- read.csv("../data/scijournal_change_radius.csv")
nohop <- nohop %>%
  mutate(relative_time = relative_time/1000) %>%
  filter(relative_time <= 20)

ideal_control <- read.csv("../data/scijournal_spin-hop_ideal-control.csv")
ideal_control <- ideal_control %>%
  mutate(relative_time = relative_time/1000) %>%
  filter(relative_time <= 20)

ideal_event <- read.csv("../data/scijournal_spin-hop_ideal-change.csv")
ideal_event <- ideal_event %>%
  mutate(relative_time = relative_time/1000) %>%
  filter(relative_time <= 20)
```

```{r functions}

# Define the rows pertaining to a few different neighborhoods
one_neighs_crime <- function(name) {
  # Retrieve crime from one neighborhood
  tmp <- modeldf %>%
  filter(neigh == name)
  out <- tmp$crime
  # Label vector with dates for later retieval
  names(out) <- tmp$date
  return(out)
}

# Function for modeling one neighborhood with one other as covariate
model_and_plot <- function(response, covariate) {
  # Get neighbhorhoods' data
  y <- one_neighs_crime(response)
  x1 <- one_neighs_crime(covariate)

  # Store in df
  data <- data.frame(y = y,
                     x1 = x1)

  # Set date series
  dates.er <- as.Date(names(y), format = "%F")

  # Create zoo object for the model
  data <- zoo(data, dates.er)

  # Model
  impact <- CausalImpact(data, pre.period, post.period)

  # Plot
  p <- plot(impact) +
    labs(title = paste("The Effect of SeeClickFix on Crime in ", response, sep = ""),
         subtitle = paste("Crime in ", covariate," as a covariate", sep = ""))

  # Return the model object and plot for further analyses
  out <- list(impact, p)
  return(out)
}

```

```{r set periods, echo=FALSE}
# Define the date at which SCF began to be used
intervention.date <- as.Date("2008-03-01", format = "%F")

# Find the month after the intervention date
d <- ymd(intervention.date)
nextmo <- d %m+% months(1)

# Define pre and post intervention periods
pre.period <- c(min(modeldf$date), intervention.date)
post.period <- c(nextmo, max(modeldf$date))
```

# Panel 4A - aggregate all of Newhaven
```{r}
aggnew <- modeldf %>%
  group_by(date) %>%
  summarize(crime = sum(crime))

aggnew <- zoo(aggnew$crime, aggnew$date)

aggimp <- CausalImpact(aggnew, pre.period = pre.period, post.period = post.period)

plot(aggimp, c("original", "cumulative")) 
  # ggsave("../figures/causal-impact_newhaven_allneigh.svg", width = 10) +
  # ggsave("../figures/causal-impact_newhaven_allneigh.png", width = 10)
```

# New 4A - East Rock no covariates
```{r}
justeast <- modeldf %>%
  filter(neigh == "wooster square/mill river")
justeast <- zoo(justeast$crime, justeast$date)

eastcaus <- CausalImpact(justeast, pre.period = pre.period, post.period = post.period)

plot(eastcaus, c("original", "cumulative")) 
  # ggsave("../figures/causal-impact_wooster.svg", width = 10)+
  # ggsave("../figures/causal-impact_wooster.png", width = 10)
```

# Panel 4C - single neighborhood with covariate
```{r}
# High user (east rock) with low user (west rock) as covariate
er.v.wr <- model_and_plot("wooster square/mill river", "west river")
print(er.v.wr)[[2]]
```

```{r}
covnew <- modeldf %>%
  filter(neigh == "wooster square/mill river" | neigh == "west river") %>%
  mutate(neigh = gsub(" ", ".", neigh),
         neigh = gsub("/", ".", neigh)) %>%
  dplyr::select(date, neigh, crime) %>%
  spread(key = neigh, value = crime) %>%
  select(date, `wooster.square.mill.river`, west.river)

covnew <- zoo(covnew[, -1], covnew$date)

# rownames(covnew) <- covnew$date

covimp <- CausalImpact(covnew, pre.period = pre.period, post.period = post.period)

plot(covimp, c("original", "cumulative")) 
```

```{r}
# png("../figures/compar-east-west.png")

plot(covnew)

# dev.off
```

# New 4c: Include covariate line
```{r}
test <- plot(covimp, c("original", "cumulative"))[['data']]

addcov <- as.data.frame(cbind(time = as.character(index(covnew)), 
                              covar = coredata(covnew$west.river), 
                              metric = "original",
                              series = "covariate"), stringsAsFactors = FALSE) %>%
  mutate(time = as.Date(time),
         covar = as.numeric(covar))


datcov <- test %>%
  # mutate(series = "focus") %>%
  left_join(addcov, by = c("time", "metric")) %>%
  mutate(series = ifelse(is.na(series), "focus", series))


```

```{r}

datcov %>%
  mutate(metric = fct_relevel(metric, "original", "cumulative")) %>%
  # spread(key = series, value = response) %>%
  ggplot(aes(x = time)) + theme_bw(base_size = 15) +
  xlab("") + ylab("") + 
  facet_grid(vars(metric), scales = "free_y") + 
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = "SlateGray2") +
  geom_vline(xintercept = pre.period[2],
                      colour = "darkgrey", size = 0.8, linetype = "dashed") +
  geom_line(aes(y = baseline),
                     colour = "darkgrey", size = 0.8, linetype = "solid", 
                     na.rm = TRUE) + 
  geom_line(aes(y = mean), size = 0.6, colour = "darkblue", linetype = "dashed",
                     na.rm = TRUE) + 
  geom_line(aes(y = response, color = "darkgreen"), size = 0.6,  na.rm = TRUE, show.legend = FALSE) +
  geom_line(aes(y = covar, color = "yellow"), size = 0.6,  na.rm = TRUE, show.legend = FALSE) +
  scale_color_manual(breaks = c("darkgreen", "yellow"), values = c("darkgreen", "yellow"))
  # ggsave("../figures/causal-impact_newhaven_woostwestriv.svg", width = 10)+
  # ggsave("../figures/causal-impact_newhaven_woostwestriv.png", width = 10)
```

# test for better covariate sets
```{r}
model_and_plot("east rock", "newhallville")
```

# Science journal figure

## Format series

```{r set up pre and post intervention definitions}
nohop <- nohop %>%
  mutate(modfeed = ifelse(relative_time > 10, NA, LinearAccelerometerSensor))
nohop.modfeed <- nohop$modfeed

nohop.pre <- c(1,175)
nohop.post <- c(176,349)
```

```{r chose measurements from time points closest to the second marks to combine control and event series}
ideal_control_1 <- ideal_control %>%
  mutate(x = round(relative_time, 1),
         y = abs(relative_time - x))

ideal_control_1 <- ideal_control_1 %>%
  group_by(x) %>%
  summarise(y = min(y)) %>%
  left_join(ideal_control_1)

ideal_event_1 <- ideal_event %>%
  mutate(x = round(relative_time, 1),
         y = abs(relative_time - x))

ideal_event_1 <- ideal_event_1 %>%
  group_by(x) %>%
  summarise(y = min(y)) %>%
  left_join(ideal_event_1)

ideal_set <- ideal_control_1 %>%
  mutate(lincont = LinearAccelerometerSensor) %>%
  dplyr::select(x, lincont) %>%
  left_join(ideal_event_1) %>%
  dplyr::select(x, LinearAccelerometerSensor, lincont)

period <- ideal_set$x <= 10.5
table(period)
pre.period.ideal <- c(1, 95)
post.period.ideal <- c(96, 96+108)
```

## Run causal impact

```{r}

# Change radius of spin without adding noise from jump.
no_hop.res <- CausalImpact(nohop$LinearAccelerometerSensor, nohop.pre, nohop.post)


# Include jump for noise.
jumpnocov.res <- CausalImpact(ideal_set$LinearAccelerometerSensor, 
                              pre.period = pre.period.ideal, post.period = post.period.ideal)

# Include a covariate series where the radius was not changed and the jump occured.
ideal.res <- CausalImpact(ideal_set[,-1], pre.period.ideal, post.period.ideal)

```

## Assemble

```{r}
with_cont.plot <- plot(ideal.res , c("original", "cumulative"))

no_hop.plot <- plot(no_hop.res, c("original", "cumulative"))

hop.plot <- plot(jumpnocov.res, c("original", "cumulative"))
```


```{r}
theme_set(theme_pubr())

figure <- ggarrange(no_hop.plot, hop.plot, with_cont.plot,
                    labels = c("A", "B", "C"),
                    ncol = 1, nrow = 3,
                    align = "v")

figure
# ggsave(plot(figure), filename = "../figures/causal-impact_spin_panel-figure.pdf", dev = "pdf", height = 8, width = 6)
```


# p.values

```{r}
summary(no_hop.res)

summary(jumpnocov.res)

summary(ideal.res)
```

```{r}
summary(aggimp)

summary(eastcaus)

summary(covimp)
```
